# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'KDInstagram' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for KDInstagram
    pod 'SnapKit'
    pod 'Nantes'
    pod 'YPImagePicker'
    pod 'FlexiblePageControl'
    pod 'RxSwift'
    pod 'RxCocoa'
    pod 'RxDataSources'
    pod 'lottie-ios'
    pod 'GrowingTextView', '0.7.2'

  target 'KDInstagramTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'KDInstagramUITests' do
    # Pods for testing
  end

end
